# Project-wide Gradle settings
newArchEnabled=false
hermesEnabled=true

# AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=false

# Increase JVM memory
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Gradle performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# React Native specific
reactNativeArchitectures=armeabi-v7a,arm64-v8a

# Kotlin
kotlin.code.style=official

# Android features
android.nonTransitiveRClass=false
android.nonFinalResIds=false